# Generated by Django 5.1.15 on 2026-07-26 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=60)),
                ('content_type', models.CharField(default='text/plain', max_length=60)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('delivered', 'Delivered')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='fleet.device')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='ingest_comm_device__87e588_idx')],
            },
        ),
    ]
