# Generated by Django 5.1.15 on 2026-08-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('overspeed', 'Overspeed'), ('geofence_breach', 'Geofence breach'), ('low_fuel', 'Low fuel'), ('fuel_fill', 'Fuel fill'), ('fuel_theft', 'Fuel theft'), ('tamper', 'Tamper'), ('device_offline', 'Device offline'), ('sensor_fault', 'Sensor fault'), ('idle_too_long', 'Idle too long')], max_length=30),
        ),
    ]
