# Generated by Django 5.1.15 on 2026-08-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicledocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='local_name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
