# Generated by Django 5.1.15 on 2026-08-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_local_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DriverAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half day'), ('leave', 'On leave')], default='present', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='fleet.driver')),
            ],
            options={
                'verbose_name_plural': 'driver attendance',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('driver', 'date'), name='uniq_attendance_per_day')],
            },
        ),
    ]
