# Generated by Django 5.1.15 on 2026-07-26 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('owner', 'Owner'), ('manager', 'Manager'), ('driver', 'Driver')], max_length=20)),
                ('module', models.CharField(max_length=40)),
                ('allowed', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'module'), name='uniq_role_module')],
            },
        ),
        migrations.CreateModel(
            name='UserModuleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=40)),
                ('allowed', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'module'), name='uniq_user_module')],
            },
        ),
    ]
