# Generated by Django 5.1.15 on 2026-08-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_can_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='max_idle_minutes',
            field=models.PositiveIntegerField(default=45, help_text='Alert when a vehicle sits stopped (not moving) this long.'),
        ),
    ]
