# Generated by Django 5.1.15 on 2026-09-30 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_view_as_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('summary', models.CharField(max_length=300)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ok', models.BooleanField(default=True)),
                ('portal', models.CharField(blank=True, max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.company')),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['actor', '-at'], name='core_auditl_actor_i_b5d7d1_idx'), models.Index(fields=['actor_role', '-at'], name='core_auditl_actor_r_6d2e3d_idx')],
            },
        ),
    ]
