# Generated by Django 5.1.15 on 2026-08-02 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('rc', 'Registration (RC)'), ('insurance', 'Insurance'), ('permit', 'Permit'), ('puc', 'Pollution (PUC)'), ('fitness', 'Fitness certificate'), ('other', 'Other')], max_length=20)),
                ('number', models.CharField(blank=True, max_length=80)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('expiry_date'), nulls_last=True)],
            },
        ),
    ]
