# Generated by Django 5.1.15 on 2026-07-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rolepermission_usermoduleoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_edit',
            field=models.BooleanField(default=False, help_text='If on, this user may make changes (create/edit/delete). Super Admins can always edit regardless of this flag.'),
        ),
    ]
