# Generated by Django 5.1.15 on 2026-08-03 11:33

from django.db import migrations, models

_ROLE_RENAME = {"owner": "dealer", "driver": "pilot", "superadmin": "admin"}


def _forwards(apps, schema_editor):
    User = apps.get_model("core", "User")
    RolePermission = apps.get_model("core", "RolePermission")
    for old, new in _ROLE_RENAME.items():
        User.objects.filter(role=old).update(role=new)
        RolePermission.objects.filter(role=old).update(role=new)


def _backwards(apps, schema_editor):
    User = apps.get_model("core", "User")
    RolePermission = apps.get_model("core", "RolePermission")
    for old, new in _ROLE_RENAME.items():
        User.objects.filter(role=new).update(role=old)
        RolePermission.objects.filter(role=new).update(role=old)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companysettings_max_idle_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dealer', 'Dealer'), ('manager', 'Manager'), ('pilot', 'Pilot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_edit',
            field=models.BooleanField(default=False, help_text='If on, this user may make changes (create/edit/delete). Admins can always edit regardless of this flag.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dealer', 'Dealer'), ('manager', 'Manager'), ('pilot', 'Pilot')], default='dealer', max_length=20),
        ),
        migrations.RunPython(_forwards, _backwards),
    ]
